---

- name: Ensure key for repository exists.
  rpm_key:
    state: present
    key: "{{ postgresql_rpm_key_url }}"

- name: Ensure repository for postgres {{ postgresql_version }} is installed.
  yum_repository:
    description: "PostgreSQL {{ postgresql_version }} for RHEL/CentOS $releasever - $basearch"
    file: /etc/yum.repos.d/postgres_{{ postgresql_version }}.repo
    name: "pgdg{{ postgresql_version }}"
    baseurl: "https://download.postgresql.org/pub/repos/yum/{{ postgresql_version }}/redhat/rhel-$releasever-$basearch"
    gpgcheck: yes
  register: _repofile

- name: Ensure repository for postgres-common is installed.
  yum_repository:
    description: "PostgreSQL common for RHEL/CentOS $releasever - $basearch"
    file: /etc/yum.repos.d/postgres_{{ postgresql_version }}.repo
    name: pgdg-common
    baseurl: "https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-$releasever-$basearch"
    gpgcheck: yes

- name: Ensure PostgreSQL packages are installed.
  yum:
    name: "{{ postgresql_packages }}"
    state: present
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"
    # Don't let postgresql-contrib cause the /usr/bin/python symlink
    # to be installed, which breaks later Ansible runs on Fedora 30,
    # and affects system behavior in multiple ways.
    exclude: python-unversioned-command

- name: Ensure PostgreSQL Python libraries are installed.
  yum:
    name: "{{ postgresql_python_library }}"
    state: present
    enablerepo: "{{ postgresql_enablerepo | default(omit, true) }}"
